version: "3.8"

services:
  # PostgreSQL for user-service
  user-db:
    image: postgres
    container_name: user-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data/user-db:/var/lib/postgresql/data

  # PostgreSQL for order-service
  order-db:
    image: postgres
    container_name: order-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data/order-db:/var/lib/postgresql/data

  # MongoDB for product-service
  product-db:
    image: mongo
    container_name: product-db
    ports:
      - "27017:27017"
    volumes:
      - ./data/product-mongo:/data/db

  # Adminer for inspecting Postgres
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
